

  const Myfollowingdata = [
    { user: "talha", datefollowed: "22/22/22" },
    { user: "john_doe", datefollowed: "12/15/21" },
    { user: "sara_123", datefollowed: "01/10/22" },
    { user: "alex_smith", datefollowed: "05/03/21" },
    { user: "emma_j", datefollowed: "08/18/22" },
    { user: "mike23", datefollowed: "11/30/21" },
    { user: "lily_m", datefollowed: "09/25/22" },
    { user: "chris_789", datefollowed: "03/12/22" },
    { user: "jessie_22", datefollowed: "07/07/21" },
    { user: "ryan_p", datefollowed: "02/28/22" },
    { user: "olivia_r", datefollowed: "04/14/21" },
    { user: "max_k", datefollowed: "10/05/22" },
    { user: "grace_123", datefollowed: "06/20/21" },
    { user: "david_w", datefollowed: "09/08/22" },
    { user: "bella_c", datefollowed: "01/02/21" },
    { user: "jason_m", datefollowed: "07/15/22" },
    { user: "lisa_88", datefollowed: "11/22/21" },
    { user: "peter_s", datefollowed: "08/09/22" },
    { user: "emily_f", datefollowed: "04/01/21" },
    { user: "mark_p", datefollowed: "12/07/22" },
    { user: "jason_m", datefollowed: "07/15/22" },
    { user: "lisa_88", datefollowed: "11/22/21" },
    { user: "peter_s", datefollowed: "08/09/22" },
    { user: "emily_f", datefollowed: "04/01/21" },
    { user: "mark_p", datefollowed: "12/07/22" },
    { user: "jason_m", datefollowed: "07/15/22" },
    { user: "lisa_88", datefollowed: "11/22/21" },
    { user: "peter_s", datefollowed: "08/09/22" },
    { user: "emily_f", datefollowed: "04/01/21" },
    { user: "mark_p", datefollowed: "12/07/22" },    
    { user: "jason_m", datefollowed: "07/15/22" },
    { user: "lisa_88", datefollowed: "11/22/21" },
    { user: "peter_s", datefollowed: "08/09/22" },
    { user: "emily_f", datefollowed: "04/01/21" },
    { user: "mark_p", datefollowed: "12/07/22" },
    { user: "jason_m", datefollowed: "07/15/22" },
    { user: "lisa_88", datefollowed: "11/22/21" },
    { user: "peter_s", datefollowed: "08/09/22" },
    { user: "emily_f", datefollowed: "04/01/21" },
    { user: "mark_p", datefollowed: "12/07/22" },    
    { user: "jason_m", datefollowed: "07/15/22" },
    { user: "lisa_88", datefollowed: "11/22/21" },
    { user: "peter_s", datefollowed: "08/09/22" },
    { user: "emily_f", datefollowed: "04/01/21" },
    { user: "emily_f", datefollowed: "04/01/21" },
  ];
  const Alltweets=[
    { user: "Doy Dagwell", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat placeat dolorem sequi velit sit nulla ducimus optio temporibus deserunt aperiam dolorum animi necessitatibus dolores, nisi suscipit harum minus pariatur illo.    ", date: "02/21/2023", likes: 44 },
    { user: "August Fridd", content: "afridd2@reverbnation.com", date: "05/14/2023", likes: 58 },
    { user: "Georg Boteman", content: "gboteman3@sakura.ne.jp", date: "08/02/2023", likes: 72 },
    { user: "Sallyanne Westmancoat", content: "swestmancoat4@tuttocitta.it", date: "01/10/2023", likes: 31 },
    { user: "Garik Frushard", content: "gfrushard5@state.gov", date: "11/10/2023", likes: 57 },
    { user: "Hamil Geertje", content: "hgeertje6@webs.com", date: "04/25/2023", likes: 69 },
    { user: "Fanni Maps", content: "fmaps7@abc.net.au", date: "06/10/2023", likes: 80 },
    { user: "Tressa Brodbin", content: "tbrodbin8@craigslist.org", date: "08/29/2023", likes: 42 },
    { user: "Cordy Jerrom", content: "cjerrom9@newyorker.com", date: "09/07/2023", likes: 59 },
    { user: "Gretel Dugan", content: "gdugana@cbc.ca", date: "04/18/2023", likes: 84 },
    { user: "Hillel Gallatly", content: "hgallatlyb@trellian.com", date: "08/18/2023", likes: 67 },
    { user: "Lulu Brunelli", content: "lbrunellic@sohu.com", date: "05/18/2023", likes: 28 },
    { user: "Vale Haddrell", content: "vhaddrelld@google.es", date: "10/02/2023", likes: 55 },
    { user: "Cissy Parry", content: "cparrye@vistaprint.com", date: "12/15/2023", likes: 66 },
    { user: "Melony Iggo", content: "miggof@time.com", date: "09/13/2023", likes: 32 },
    { user: "Tory Tembridge", content: "ttembridgeg@zimbio.com", date: "01/31/2024", likes: 94 },
    { user: "Carce Effnert", content: "ceffnerth@opera.com", date: "12/22/2022", likes: 78 },
    { user: "Meghan Karlsen", content: "mkarlseni@opensource.org", date: "09/28/2023", likes: 47 },
    { user: "Morissa Crystal", content: "mcrystalj@de.vu", date: "03/25/2023", likes: 62 },
    { user: "Wilma Kanwell", content: "wkanwellk@newsvine.com", date: "08/30/2023", likes: 88 },
    { user: "Arabelle Filippazzo", content: "afilippazzol@usatoday.com", date: "01/08/2024", likes: 25 },
    { user: "Devland Senecaux", content: "dsenecauxm@desdev.cn", date: "12/17/2022", likes: 51 },
    { user: "Cornell Feathersby", content: "cfeathersbyn@abc.net.au", date: "09/08/2023", likes: 65 },
    { user: "Etta Prettejohns", content: "eprettejohnso@51.la", date: "11/07/2022", likes: 43 },
    { user: "Shaw Oxshott", content: "soxshottp@dion.ne.jp", date: "02/06/2024", likes: 97 },
    { user: "Antoni Elderbrant", content: "aelderbrantq@weather.com", date: "09/17/2023", likes: 22 },
    { user: "Alli Aggiss", content: "aaggissr@upenn.edu", date: "11/05/2023", likes: 14 },
    { user: "Teirtza Crombie", content: "tcrombies@angelfire.com", date: "08/12/2023", likes: 80 },
    { user: "Ethan Yoodall", content: "eyoodallt@ed.gov", date: "11/29/2022", likes: 92 },
    { user: "Ravid Liffe", content: "rliffeu@netlog.com", date: "09/24/2023", likes: 39 },
    { user: "Babbette Critcher", content: "bcritcherrq@so-net.ne.jp", date: "02/17/2023", likes: 64 },
    { user: "Lorain Strickler", content: "lstricklerrr@amazonaws.com", date: "10/30/2023", likes: 67 }
  ]
  const Rmt=[
  ]
  const Myfollowerdata = [
    { user: "talha",     datefollowed: "22/22/22" },
    { user: "john_doe",  datefollowed: "12/15/21" },
    { user: "sara_123",  datefollowed: "01/10/22" },
    { user: "alex_smith", datefollowed: "05/03/21" },
    { user: "emma_j",    datefollowed: "08/18/22" },
    { user: "mike23",    datefollowed: "11/30/21" },
    { user: "lily_m",    datefollowed: "09/25/22" },
    { user: "chris_789", datefollowed: "03/12/22" },
    { user: "jessie_22", datefollowed: "07/07/21" },
    { user: "ryan_p",    datefollowed: "02/28/22" },
    { user: "olivia_r",  datefollowed: "04/14/21" },
    { user: "max_k",      datefollowed: "10/05/22" },
    { user: "grace_123", datefollowed: "06/20/21" },
    { user: "david_w",    datefollowed: "09/08/22" },
    { user: "bella_c",    datefollowed: "01/02/21" },
    { user: "jason_m",    datefollowed: "07/15/22" },
    { user: "lisa_88",    datefollowed: "11/22/21" },
    { user: "peter_s",    datefollowed: "08/09/22" },
    { user: "emily_f",     datefollowed: "04/01/21" },
    { user: "mark_p",      datefollowed: "12/07/22" },
    { user: "jason_m",   datefollowed: "07/15/22" },
    { user: "lisa_88",   datefollowed: "11/22/21" },
    { user: "peter_s",   datefollowed: "08/09/22" },
    { user: "emily_f",   datefollowed: "04/01/21" },
    { user: "mark_p",   datefollowed: "12/07/22" },
    { user: "jason_m",   datefollowed: "07/15/22" },
    { user: "lisa_88",  datefollowed: "11/22/21" },
    { user: "peter_s",  datefollowed: "08/09/22" },
    { user: "emily_f",   datefollowed: "04/01/21" },
    { user: "mark_p",   datefollowed: "12/07/22" },    
    { user: "jason_m",   datefollowed: "07/15/22" },
    { user: "lisa_88",  datefollowed: "11/22/21" },
    { user: "peter_s",  datefollowed: "08/09/22" },
    { user: "emily_f",   datefollowed: "04/01/21" },
    { user: "mark_p",   datefollowed: "12/07/22" },
    { user: "jason_m",   datefollowed: "07/15/22" },
    { user: "lisa_88",   datefollowed: "11/22/21" },
    { user: "peter_s",   datefollowed: "08/09/22" },
    { user: "emily_f",   datefollowed: "04/01/21" },
    { user: "mark_p",   datefollowed: "12/07/22" },    
    { user: "jason_m",   datefollowed: "07/15/22" },
    { user: "lisa_88",  datefollowed: "11/22/21" },
    { user: "peter_s",  datefollowed: "08/09/22" },
    { user: "emily_f",   datefollowed: "04/01/21" },
    { user: "mark_p",  datefollowed: "12/07/22" },
  ];
  const Rmuser=[]
  const Users = [
    { user: "talha",        },
    { user: "john_doe",     },
    { user: "sara_123",   },
    { user: "alex_smith",   },
    { user: "emma_j",      },
    { user: "mike23",      },
    { user: "lily_m",      },
    { user: "chris_789",    },
    { user: "jessie_22",   },
    { user: "ryan_p",    },
    { user: "olivia_r",   },
    { user: "max_k",       },
    { user: "grace_123",    },
    { user: "david_w",    },
    { user: "bella_c",    },
    { user: "jason_m",    },
    { user: "lisa_88",    },
    { user: "peter_s",    },
    { user: "emily_f",      },
    { user: "mark_p",      },
    { user: "jason_m",    },
    { user: "lisa_88",    },
    { user: "peter_s",    },
    { user: "emily_f",   },
    { user: "mark_p",  },
    { user: "jason_m",   },
    { user: "lisa_88", } ,
    { user: "peter_s",  },
    { user: "emily_f",   },
    { user: "mark_p",   },    
    { user: "jason_m",   },
    { user: "lisa_88",  }  ,
    { user: "peter_s",  },
    { user: "emily_f",   },
    { user: "mark_p",   },
    { user: "jason_m",     },
    { user: "lisa_88",    },
    { user: "peter_s",    },
    { user: "emily_f",    },
    { user: "mark_p",   },    
    { user: "jason_m",   },
    { user: "lisa_88",  },
    { user: "peter_s",  },
    { user: "emily_f",    },
    { user: "mark_p",  },
  ];
  export {Alltweets,Myfollowingdata,Myfollowerdata,Users,Rmt,Rmuser};
